apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: result
  name: result
spec:
  type: NodePort
  ports:
  - name: "5001"
    port: 5001
    targetPort: 80
  selector:
    io.kompose.service: result