apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: #TUFIN_KITE_NAMESPACE#
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: monitor
      labels:
        name: monitor
      namespace: #TUFIN_KITE_NAMESPACE#
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRole
    metadata:
      name: monitor
      labels:
        name: monitor
    rules:
      - apiGroups:
          - ''
        resources:
          - pods
        verbs:
          - get
          - list
          - watch
          - delete
      - apiGroups:
          - ''
        resources:
          - services
          - nodes
          - namespaces
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - extensions
        resources:
          - deployments
          - daemonsets
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - extensions
        resources:
          - deployments/scale
        verbs:
          - get
          - update
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRoleBinding
    metadata:
      name: monitor
      namespace: #TUFIN_KITE_NAMESPACE#
      labels:
        name: monitor
    roleRef:
      kind: ClusterRole
      name: monitor
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: monitor
        namespace: #TUFIN_KITE_NAMESPACE#
  - apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: monitor
      labels:
        app: monitor
      namespace: #TUFIN_KITE_NAMESPACE#
    spec:
      minReadySeconds: 5
      selector:
        matchLabels:
          app: monitor
      template:
        metadata:
          labels:
            app: monitor
        spec:
          containers:
            - name: monitor
              args:
                - 'kite.#TUFIN_KITE_NAMESPACE#:80'
              command:
                - /home/tufin/monitor
              env:
                - name: KUBERNETES_NODENAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: spec.nodeName
              image: #MONITOR_IMAGE#
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: 100m
                  memory: 100Mi
              securityContext:
                privileged: true
              volumeMounts:
                - name: sys-kernel-debug
                  mountPath: /sys/kernel/debug
                - name: docker-socket
                  mountPath: /var/run/docker.sock
          dnsPolicy: ClusterFirstWithHostNet
          hostNetwork: true
          hostPID: true
          serviceAccountName: monitor
          tolerations:
            - effect: NoSchedule
              operator: Exists
          volumes:
            - name: sys-kernel-debug
              hostPath:
                path: /sys/kernel/debug
            - name: docker-socket
              hostPath:
                path: /var/run/docker.sock
      updateStrategy:
        type: RollingUpdate
