---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kite
  namespace: #TUFIN_KITE_NAMESPACE#
---
apiVersion: v1
kind: Service
metadata:
  name: kite
  namespace: #TUFIN_KITE_NAMESPACE#
  labels:
    app: kite
spec:
  selector:
    app: kite
  ports:
  - name: syslog
    port: 6062
    targetPort: 1514
    protocol: UDP
  - name: grpc
    port: 81
    targetPort: 6061
    protocol: TCP
  - name: http
    port: 80
    targetPort: 6060
    protocol: TCP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kite
  namespace: #TUFIN_KITE_NAMESPACE#
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kite
  template:
    metadata:
      labels:
        app: kite
    spec:
      serviceAccountName: kite
      containers:
      - name: kite
        image: #KITE_IMAGE#
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: IGNORED_CONFIGMAPS
          value: kube-system/ingress-gce-lock,istio-system/istio-ingress-controller-leader-istio
        - name: TUFIN_ORCA_URL
          valueFrom:
            configMapKeyRef:
              name: orca-config
              key: orca-url
        - name: TUFIN_INSTALL_CONNTRACK
          valueFrom:
            configMapKeyRef:
              name: orca-config
              key: kite-install-monitor
        - name: TUFIN_INSTALL_SYSLOG
          valueFrom:
            configMapKeyRef:
              name: orca-config
              key: kite-install-syslog
        - name: TUFIN_INSTALL_DNS
          valueFrom:
            configMapKeyRef:
              name: orca-config
              key: kite-install-dns
        - name: TUFIN_INSTALL_ISTIO
          valueFrom:
            configMapKeyRef:
              name: orca-config
              key: kite-install-istio
        - name: TUFIN_INSTALL_DOCKER_PUSHER
          valueFrom:
            configMapKeyRef:
              name: orca-config
              key: kite-install-pusher
        - name: TUFIN_INSTALL_KUBE_EVENTS_WATCHER
          valueFrom:
            configMapKeyRef:
              name: orca-config
              key: kite-install-watcher
        - name: TUFIN_GURU_URL
          valueFrom:
            configMapKeyRef:
              name: orca-config
              key: guru-url
        - name: DOMAIN
          valueFrom:
            configMapKeyRef:
              name: orca-config
              key: kite-domain
        - name: PROJECT
          valueFrom:
            configMapKeyRef:
              name: orca-config
              key: kite-project
        - name: TUFIN_DOCKER_REPO_URL
          valueFrom:
            configMapKeyRef:
              name: orca-config
              key: registry-url
        - name: TUFIN_INSTALL_NETWORK_POLICY
          valueFrom:
            configMapKeyRef:
              name: orca-config
              key: kube-network-policy
        - name: CRT
          valueFrom:
            secretKeyRef:
              name: #TUFIN_KITE_SECRETS_NAME#
              key: guru-crt
        - name: TUFIN_DOCKER_REPO_USERNAME
          valueFrom:
            secretKeyRef:
              name: #TUFIN_KITE_SECRETS_NAME#
              key: docker-repo-username
        - name: TUFIN_DOCKER_REPO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: #TUFIN_KITE_SECRETS_NAME#
              key: guru-api-key
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: #TUFIN_KITE_SECRETS_NAME#
              key: guru-api-key
        ports:
        - containerPort: 6060
        - containerPort: 6061
        - containerPort: 6062
          protocol: UDP
        volumeMounts:
        - mountPath: /tmp/.local
          name: cache-volume
      volumes:
      - name: cache-volume
        emptyDir: {}
