---
apiVersion: v1
kind: Secret
metadata:
  name: #TUFIN_KITE_SECRETS_NAME#
  namespace: #TUFIN_KITE_NAMESPACE#
type: Opaque
data:
  guru-crt: #TUFINIO_CRT#
  guru-api-key: #GURU_API_KEY#
  docker-repo-username: #DOCKER_REPO_USERNAME#